This is makeindex, version 2.18 [MiKTeX 26.2].
Scanning style file ./WissBer_PA_SA_BA.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file .\WissBer_PA_SA_BA.acn....done (90 entries accepted, 0 rejected).
Sorting entries....done (636 comparisons).
Generating output file .\WissBer_PA_SA_BA.acr....done (74 lines written, 0 warnings).
Output written in .\WissBer_PA_SA_BA.acr.
Transcript written in .\WissBer_PA_SA_BA.alg.
